### ISSUE TITLE
Content?

### ISSUE THREAD

**Issue by Thanerik** [surdoparasurdo/awesome-sign-language#1]
There are not that much projects and ressources here in the 🙌awesome list ;-)

**Comment by robsonmafra** [comment]
@Thanerik I have started that last week. I have a few personal projects and contents related to Sign Language, this is why I started this list and I will update the content soon :)

If you have suggestions, feel free to send me or open a pull request adding that.

**Comment by Thanerik** [comment]
Not bad! Didn't see that you just started this repository, so I'll follow it along and see what there would come of awesome sign language projects. Maybe I have some to contribute - lets see ;-)
